version: '3.8'
services:
  postgres_db:
    image: postgis/postgis:16-3.4
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
    restart: always
    networks:
      - database

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    ports: 
      - 8080:80
    env_file:
      - .env
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres_db
    restart: always
    networks:
      - database
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - 5173:5173
    restart: always
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - database

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - postgres_db
    ports:
      - 8000:8000
    env_file:
      - ./.env
    volumes:
      - ./backend:/app
    restart: always
    networks:
      - database
volumes:
  postgres_data: 
  pgadmin_data:
networks:
  database:
    driver: bridge